### PR TITLE
Auto setup Linux target - make manual target modifications obsolete

### PR DESCRIPTION
**Pull request by cadivus**
Right now, you need to manually edit files in the Linux target. This PR resolves that so that you just add webview_cef to your pubspec and are good to go.

...and rename the build test workflow.

### CODE REVIEW

**Comment by cadivus** [comment]
@hlwhl Thanks a lot for merging! Could you please create a version bump and another tag for a pub.dev release?

**Comment by hlwhl** [comment]
> @hlwhl Thanks a lot for merging! Could you please create a version bump and another tag for a pub.dev release?

v0.2.2 is rolling out.

**Comment by cadivus** [comment]
@hlwhl Thanks! I think it failed because no one bumped the version in https://github.com/hlwhl/webview_cef/blob/main/pubspec.yaml

**Comment by cadivus** [comment]
@hlwhl Sorry for bothering again, but after the bump you also need to create a new tag for triggering the release pipeline again.

**Comment by hlwhl** [comment]
> @hlwhl Sorry for bothering again, but after the bump you also need to create a new tag for triggering the release pipeline again.

Sorry for lack of time. A new publishing (v0.2.2) is trigged.

**Comment by hlwhl** [comment]
By the way, do you have intrest of maintaining this repo?

**Comment by cadivus** [comment]
> Sorry for lack of time. A new publishing (v0.2.2) is trigged.

No problem, I know this problem. Thanks a lot!

> By the way, do you have intrest of maintaining this repo?

Sure. I can't make promises, but I try my best.

**Pull request merged**
