### PR TITLE
navigation interception

### PR DESCRIPTION
**Pull request by patel0712**
@SinyimZhi 
@hlwhl 
@BullsEye34 

 Issue : #134  #127

I override onBeforeBrowse method in order to intercept url in webview_handler.cc file

hey i implement url interception as of my knowledge but it works only when i trigger url from searchbar and enter it will prevented but same link when i will click inside webview or redirect with flow its not working

that means after giving decision prevent for any url it should be prevented but in code i modify its not working as expected.

please help me to implement this feature.
also if possible can we stay in touch with any social media so i want to learn from you
and develope my skills.
my email : jeetnadiyadara07@gmail.com

### CODE REVIEW

**Comment by SinyimZhi** [comment]
Sorry, I've been busy these days. I'll take a look sometime.

**Comment by patel0712** [comment]
It's ok I know you are busy @SinyimZhi .

If possible please take a look at this and guide me where I'm mistaken. And what I have to do to fix this issue.

**Comment by patel0712** [comment]
> @SinyimZhi @hlwhl @BullsEye34
> 
> Issue : #134 #127
> 
> I override onBeforeBrowse method in order to intercept url in webview_handler.cc file
> 
> hey i implement url interception as of my knowledge but it works only when i trigger url from searchbar (or we can say that load url with loadUrl method) and enter it will prevented but same link when i will click inside webview or redirect with flow its not working
> 
> that means after giving decision prevent for any url it should be prevented but in code i modify its not working as expected.
> 
> please help me to implement this feature. also if possible can we stay in touch with any social media so i want to learn from you and develope my skills. my email : [jeetnadiyadara07@gmail.com](mailto:jeetnadiyadara07@gmail.com)

**Comment by patel0712** [comment]
Hey 
Can you please tell me when you will going to implement this navigation delegate like feature in webview_cef package?

Please tell me if possible?

**Comment by patel0712** [comment]
Ok fine if you don't even tell me 

Sorry for wasting your time.

**Comment by SinyimZhi** [comment]
> Ok fine if you don't even tell me
> 
> Sorry for wasting your time.

I'm sorry, I only had time to continue participating in this project this week. Due to too many emails, I directly checked the pull request and new issue of the project. I missed your pull request because it was in a closed status.

**Review by SinyimZhi — COMMENTED** [review]
I have conducted a preliminary review of your code, and haven't found any problems yet. However, we generally do not directly integrate the new feature code into the backbone and require detailed self testing. Do your expectations for the current code match your actual testing? Is there any unrealized part or unsolvable problem?

**Pull request closed without merging**
